######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET =
DEPENDPATH += . ../../
# INCLUDEPATH += /home/ulrich/dev/qt/AlignShop/trunk/tests/TestCrudSqlRecord /home/ulrich/dev/qt/AlignShop/trunk
INCLUDEPATH += . ../../

# Input
SOURCES += TestCrudSqlRecord.cpp CrudSqlRecord.cpp DbTable.cpp

QT += sql xmlpatterns
