######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET = 
DEPENDPATH += . /home/ulrich/dev/qt/AlignShop/trunk
INCLUDEPATH += /home/ulrich/dev/qt/AlignShop/trunk/tests/TestParseError /home/ulrich/dev/qt/AlignShop/trunk

# Input
SOURCES += TestParseError.cpp
