######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET =
DEPENDPATH += . ../../.. ../../../PrimerDesign
INCLUDEPATH += . ../../.. ../../../PrimerDesign

# Input
SOURCES += TestPrimerSet.cpp PrimerSet.cpp DnaSeq.cpp BioString.cpp BioStringValidator.cpp StrictDnaString.cpp global.cpp
