######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################
QT -= gui
CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

# Input
SOURCES += TestAnonSeq.cpp AnonSeq.cpp BioString.cpp AminoString.cpp DnaString.cpp RnaString.cpp
