######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../.. ../../models
INCLUDEPATH += . ../.. ../../models

# Input
HEADERS += AdocTreeModel.h AdocContainerFilterModel.h AdocTypeFilterModel.h
SOURCES += TestAdocContainerFilterModel.cpp AdocContainerFilterModel.cpp AdocTypeFilterModel.cpp AdocTreeModel.cpp AdocTreeNode.cpp CrudSqlRecord.cpp DbTable.cpp
QT += sql xmlpatterns
