######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

# Input
HEADERS += models/AdocTreeModel.h \
           models/AdocRnaFilterModel.h \
           models/AdocTypeFilterModel.h

SOURCES += TestAdocRnaFilterModel.cpp \
           models/AdocRnaFilterModel.cpp \
           models/AdocTypeFilterModel.cpp \
           models/AdocTreeModel.cpp \
           AdocTreeNode.cpp \
           CrudSqlRecord.cpp \
           DbTable.cpp

QT += sql xmlpatterns
