######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET =
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

# Input
SOURCES += TestObservableList.cpp \
    ../../ObservableListNotifier.cpp

HEADERS += \
    ../../ObservableListNotifier.h \
    ../../ObservableList.h
