######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../../.. ../../../PrimerDesign
INCLUDEPATH += . ../../.. ../../../PrimerDesign

# Input
SOURCES += TestPrimerPairFinder.cpp \
    DimerCalculator.cpp \
    BioString.cpp \
    DnaString.cpp \
    BioStringValidator.cpp \
    PrimerDesignInput.cpp \
    ThermodynamicCalculator.cpp \
    StrictDnaString.cpp \
    PrimerPairFinder.cpp \
    PrimerPair.cpp \
    Primer.cpp \
    global.cpp
