######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

# Input
SOURCES += TestAnonSeqFactory.cpp AnonSeqFactory.cpp AnonSeq.cpp BioString.cpp AminoString.cpp global.cpp
