######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 11:00:56 2009
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

# Input
HEADERS += SerialGenerator.h
SOURCES += TestSerialGenerator.cpp SerialGenerator.cpp
