######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 13:27:29 2009
######################################################################

CONFIG += qtestlib release
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../..
INCLUDEPATH += . ../..

# Input
SOURCES += TestBioString.cpp BioString.cpp global.cpp

QMAKE_CFLAGS_RELEASE += -O2 -march=nocona
QMAKE_CXXFLAGS_RELEASE += -O2 -march=nocona
